name: Test Mirror Without PAT

on:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Migration
        run: |
          chmod +x ./scripts/migrate.sh
          ./scripts/migrate.sh
